apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    demo: coolstore-microservice
    template: coolstore
  name: mongodb
  namespace: openshift
spec:
  lookupPolicy:
    local: false
  tags:
  - from:
      kind: DockerImage
      name: registry.redhat.io/rhscl/mongodb-32-rhel7
    generation: 2
    name: "3.2"
    referencePolicy:
      type: Source
